uses io.Output
uses data.String

data Thing {
	Data q
	}

component provides UnitTest requires Store st {
	
	int alpha
	
	bool testA()
		{
		Store stq = new Store()
		
		Item itemA = new Item(new String("hi"), "there")
		
		st.functionA("one", itemA, itemA)
		
		return true
		}
	
	void humana(int a)
		{
		alpha = a
		}
	
	Data globalA
	Data globalAR[]
	
	bool functionA(char a[], Item b)
		{
		store Thing ma = new Thing()
		
		Thing wa = ma
		
		wa.q = b
		
		globalA = ma
		
		return true
		}
	
	bool functionB(char a[], Item b)
		{
		store Thing ma = new Thing(b)
		
		return true
		}
	
	bool functionC(char a[], Item b)
		{
		store Thing ma = new Thing(new Thing(b))
		
		return true
		}
	
	bool functionD(char a[], Item b)
		{
		store Item q[] = new Item[](b)
		
		return true
		}
	
	bool functionE(char a[], Item b)
		{
		store Item q[] = new Item[1]
		
		q[0] = b
		
		return true
		}
	
	bool functionF(char a[], Item b)
		{
		store Item q[] = new Item[](new Item[](b))
		
		return true
		}
	
	bool functionG(char a[], Item b)
		{
		store Item q[] = new Item[1]
		
		Item lq[] = new Item[](b)
		
		q[0] = lq[0]
		
		return true
		}
	
	bool UnitTest:runTest()
		{
		humana(99)
		
		Item itemA = new Item(new String("hi"), "there")
		
		store Item itemB = new Item(new String("hi"), "there")
		
		if (st.functionA("one", itemA, itemB) == true) throw new Exception("Failure in test 1")
		
		if (st.functionB("one", itemA, itemB) == true) throw new Exception("Failure in test 2")
		
		if (st.functionC("one", itemA, itemB) == false) throw new Exception("Failure in test 3")
		
		if (st.functionD("one", itemA, itemB) == true) throw new Exception("Failure in test 4")
		
		if (st.functionE("one", itemA, itemB) == true) throw new Exception("Failure in test 5")
		
		if (st.functionF("one", itemA, itemB) == true) throw new Exception("Failure in test 6")
		
		if (st.functionG("one", itemA, itemB) == true) throw new Exception("Failure in test 7")
		
		return true
		}
	
	}